# Generated by Django 6.1.1 on 2026-09-29 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_file',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 29, 15, 30, 23, 906731, tzinfo=datetime.timezone.utc)),
        ),
    ]
