# Generated by Django 6.1.1 on 2026-09-29 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_file_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 29, 15, 38, 20, 218739, tzinfo=datetime.timezone.utc)),
        ),
    ]
