# Generated by Django 6.1.1 on 2026-09-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('bio', models.CharField(max_length=300)),
                ('cover_file', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
